substitutions:
 devicename: cover_office
 
esphome:
  name: cover
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret wifi_cover_fallback_ssid
    password: !secret wifi_cover_fallback_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret wifi_cover_api_pass

ota:
  password: !secret ota_password
  
sensor:
  - platform: uptime
    name: '${devicename}_uptime'
    id: uptime_sec
    internal: true

  - platform: wifi_signal
    name: '${devicename}_WiFi_Signal'
    update_interval: 60s

text_sensor:
  - platform: template
    name: '${devicename}_uptime'
    lambda: |-
      int seconds = (id(uptime_sec).state);
      int days = seconds / (24 * 3600);
      seconds = seconds % (24 * 3600); 
      int hours = seconds / 3600;
      seconds = seconds % 3600;
      int minutes = seconds /  60;
      seconds = seconds % 60;
      return { (String(days) +" д. " + String(hours) +" ч. " + String(minutes) +" мин.").c_str() };
    icon: mdi:clock
    update_interval: 113s

web_server:
  port: 80

switch:
  - platform: gpio
    pin: D2
    name: "Blinds Open Switch"
    id: open_switch
    
  - platform: gpio
    pin: D3
    name: "Blinds Close Switch"
    id: close_switch

binary_sensor:
  # https://esphome.io/components/binary_sensor/gpio.html
  - platform: gpio
    pin:
      number: D0
      mode: INPUT_PULLUP
      inverted: True
    name: "Cover Bottom Off"
    on_press:
      - switch.turn_off: close_switch
      - switch.turn_off: open_switch

      - switch.turn_on: open_switch
      - delay: 1s
      - switch.turn_off: open_switch

  - platform: gpio
    pin:
      number: D7
      mode: INPUT_PULLUP
      inverted: True
    name: "Cover Top Off"
    on_press:
      - switch.turn_off: close_switch
      - switch.turn_off: open_switch
      
      - switch.turn_on: close_switch
      - delay: 1s
      - switch.turn_off: close_switch

  - platform: gpio
    pin:
      number: D5
      mode: INPUT_PULLUP
      inverted: True
    name: "Cover button open"
    on_press:
      - switch.turn_off: close_switch
      - switch.turn_off: open_switch

      - switch.turn_on: open_switch
    on_double_click:
      - switch.turn_off: close_switch
      - switch.turn_off: open_switch

  - platform: gpio
    pin:
      number: D6
      mode: INPUT_PULLUP
      inverted: True
    name: "Cover button close"
    on_press:
      - switch.turn_off: close_switch
      - switch.turn_off: open_switch
      
      - switch.turn_on: close_switch
    on_double_click:
      - switch.turn_off: close_switch
      - switch.turn_off: open_switch 

      
cover:
  - platform: template
    name: "Window"
    open_action:
      # Cancel any previous action
      - switch.turn_off: close_switch
      # Turn the OPEN switch on briefly
      - switch.turn_on: open_switch
      - delay: 20.0s
      - switch.turn_off: open_switch
      - delay: 1.0s
      - switch.turn_on: close_switch
      - delay: 0.1s
      - switch.turn_off: close_switch
    close_action:
      - switch.turn_off: open_switch
      - switch.turn_on: close_switch
      - delay: 20.0s
      - switch.turn_off: close_switch
      - delay: 1.0s
      - switch.turn_on: open_switch
      - switch.turn_off: open_switch
    stop_action:
      - switch.turn_off: close_switch
      - switch.turn_off: open_switch
    optimistic: true
    assumed_state: true

  - platform: template
    name: "Blinds_stop"
    open_action:
      - delay: 1.0s
      - switch.turn_on: close_switch
      - delay: 0.1s
      - switch.turn_off: close_switch
    close_action:
      - delay: 1.0s
      - switch.turn_on: open_switch
      - switch.turn_off: open_switch
    stop_action:
      - switch.turn_off: close_switch
      - switch.turn_off: open_switch
    optimistic: true
    assumed_state: true
    
  - platform: time_based
    name: "Time-Based_Cover"
    open_action:
      - switch.turn_on: open_switch
    open_duration: 15.3s
    close_action:
      - switch.turn_on: close_switch
    close_duration: 15.0s
    stop_action:
      - switch.turn_off: open_switch
      - switch.turn_off: close_switch
