esphome:
  name: esp8266
  platform: ESP8266
  board: d1_mini
#  includes:
#    - my_custom_component.h
#  on_boot:
#    priority: -10
#    then:
#      - uart.write: "Hello World - onBoot"
#uart:
#  id: uart_bus
#  tx_pin: D0
#  rx_pin: D1
#  baud_rate: 9600

#custom_component:
#- lambda: |-
#    auto my_custom = new MyCustomComponent(id(uart_bus));
#    return {my_custom};

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret wifi_esp8266oled_fallback_ssid
    password: !secret wifi_esp8266oled_fallback_password

time:
  - platform: homeassistant
    id: time1
captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret wifi_esp8266oled_api_pass

ota:
  password: !secret ota_password


font:
  - file: 'Megahunt.ttf'
    id: font1
    size: 20

i2c:
  sda: GPIO4
  scl: GPIO5

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x32"
    reset_pin: GPIO16
    address: 0x3C
    lambda: |-
      it.strftime(0, 0, id(font1), "%Y-%m-%d %H:%M", id(time1).now());
